[general]
live_config_reload = true
import = [
	"~/dotfiles/alacritty/.config/alacritty/alacritty-theme/themes/tokyo_night.toml"
]

[window]
padding = { x = 5, y = 5 }
dynamic_title = true
decorations = "None"
opacity = 0.98
blur = false
startup_mode = "Windowed"

[font]
size = 16
normal = { family = "SauceCodePro Nerd Font Propo", style = "Medium" }
bold = { family = "SauceCodePro Nerd Font Propo", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font Propo", style = "Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }

[scrolling]
history = 1500
multiplier = 3 # scrolling speed

[cursor]
style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "PasteSelection" }
]

[keyboard]
bindings = [
  { key = "K", mods = "Alt", action = "ScrollLineUp" },
  { key = "J", mods = "Alt", action = "ScrollLineDown" },
  { key = "K", mods = "Alt|Shift", action = "ScrollPageUp" },
  { key = "J", mods = "Alt|Shift", action = "ScrollPageDown" },
  { key = "G", mods = "Alt", action = "ScrollToTop" },
  { key = "G", mods = "Alt|Shift", action = "ScrollToBottom" },
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "Equals", mods = "Alt", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Alt", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Alt", action = "ResetFontSize" }
]
