$bg = rgba(1a1b26ff)
$fg = rgba(a9b1d6ff)

# Accent Colors
$blue = rgba(7aa2f7ff)
$magenta = rgba(bb9af7ff)
$cyan = rgba(7dcfffff)
$green = rgba(9ece6aff)
$red = rgba(f7768eff)
$yellow = rgba(e0af68ff)

# Muted/Functional Colors
$black = rgba(414868ff)
$comment = rgba(565f89ff)
$border_active = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
$border_inactive = rgba(565f89aa)
