#include=~/.config/foot/tn.ini
include=~/.config/foot/dank-colors.ini

[main]
font=JetBrainsMono Nerd Font Propo:size=16:style=Regular
shell=/usr/bin/zsh
pad=5x2

[cursor]
blink=off
style=block

[scrollback]
lines=1000

[key-bindings]
scrollback-up-line=Mod1+k
scrollback-down-line=Mod1+j
scrollback-up-page=Mod1+Shift+k
scrollback-down-page=Mod1+Shift+j
scrollback-home=Mod1+g
scrollback-end=Mod1+Shift+g
clipboard-copy=Mod1+c
clipboard-paste=Mod1+v
font-increase=Mod1+equal
font-decrease=Mod1+minus
font-reset=Mod1+0
