# Generated by Powerlevel10k configuration wizard.
# Tokyo Night "Dark AF" Minimalist Variant (Pure style)

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
    emulate -L zsh -o extended_glob

    # Unset all configuration options.
    unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

    # Zsh >= 5.1 is required.
    [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

    # Left prompt segments.
    typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
        context                 # user@host
        dir                     # current directory
        vcs                     # git status
        command_execution_time  # previous command duration
        virtualenv              # python virtual environment
        prompt_char             # prompt symbol
    )

    # Right prompt segments (kept empty for minimalism).
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

    # Basic style options.
    typeset -g POWERLEVEL9K_BACKGROUND=
    typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
    typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
    typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
    typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=

    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

    local purple='#bb9af7'  # Accents / Prompt
    local red='#f7768e'     # Errors
    local blue='#7aa2f7'    # Directories
    local cyan='#7dcfff'    # Git changes
    local gray='#565f89'    # Comments / Context
    local yellow='#e0af68'  # Execution time
    local white='#cfc9c2'   # Main text (High contrast)

    # Prompt symbol
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=$purple
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=$red
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='❮'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

    # Directory (High contrast blue)
    typeset -g POWERLEVEL9K_DIR_FOREGROUND=$blue

    # Context (User@Host)
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE="%F{$white}%n%f%F{$gray}@%m%f"
    typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%F{$gray}%n@%m%f"
    typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_EXPANSION=

    # Execution Time (Tokyo Night Gold/Yellow)
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow

    # Git / VCS (Stealthy gray with cyan status)
    typeset -g POWERLEVEL9K_VCS_FOREGROUND=$gray
    typeset -g POWERLEVEL9K_VCS_LOADING_TEXT=
    typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0
    typeset -g POWERLEVEL9K_VCS_{INCOMING,OUTGOING}_CHANGESFORMAT_FOREGROUND=$cyan
    typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind)
    typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
    typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
    typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED}_ICON=
    typeset -g POWERLEVEL9K_VCS_DIRTY_ICON='*'
    typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=':⇣'
    typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=':⇡'
    typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=1
    typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${${${P9K_CONTENT/⇣* :⇡/⇣⇡}// }//:/ }'

    # VirtualEnv
    typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$gray
    typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
    typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

    # --- THE "DARK AF" SETTINGS ---
    # No transient prompt (user hates it)
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
    
    # Enable instant prompt for speed
    typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
    typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

    (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
